# Generated by Django 5.0.7 on 2024-07-28 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_hashtag_created_at_remove_hashtag_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
