# Generated by Django 5.0.7 on 2024-07-28 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_interest_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekhashtag',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
