# Generated by Django 5.0.7 on 2024-07-30 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_delete_interest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
