# Generated by Django 5.0.7 on 2024-08-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_weekhashtag_weekofmonth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekhashtag',
            name='weekOfMonth',
            field=models.TextField(blank=True, null=True),
        ),
    ]
