# Generated by Django 5.0.7 on 2024-07-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateedit',
            name='content',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='stateedit',
            name='emoji',
            field=models.TextField(blank=True),
        ),
    ]
