# Generated by Django 5.0.7 on 2024-07-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0003_alter_stateedit_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='stateedit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
