# Generated by Django 5.0.7 on 2024-07-30 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
