# Generated by Django 5.0.3 on 2024-07-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_account_kakaouser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='%Y%m%d/'),
        ),
    ]
