# Generated by Django 5.0.7 on 2024-07-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_phonenum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phonenum',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
