# Generated by Django 5.0.7 on 2024-07-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_phonenum'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='familycode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
