# Generated by Django 5.0.7 on 2024-07-29 05:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_family_user_family_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='familyid',
        ),
        migrations.AlterField(
            model_name='family',
            name='users',
            field=models.ManyToManyField(related_name='family', to=settings.AUTH_USER_MODEL),
        ),
    ]
