# Generated by Django 5.0.7 on 2024-07-25 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_familycode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='familycode',
        ),
    ]
