# Generated by Django 5.0.3 on 2024-07-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_groups_alter_account_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phonenum',
            field=models.IntegerField(null=True),
        ),
    ]
