# Generated by Django 5.0.7 on 2024-07-27 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_hashtag_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_interests', to='home.hashtag'),
        ),
    ]
