# Generated by Django 5.0.7 on 2024-07-28 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_weekhashtag_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interest',
        ),
    ]
