# Generated by Django 5.0.7 on 2024-07-28 18:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_family'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='user',
        ),
        migrations.AddField(
            model_name='family',
            name='users',
            field=models.ManyToManyField(related_name='families', to=settings.AUTH_USER_MODEL),
        ),
    ]
