# Generated by Django 5.0.7 on 2024-07-21 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StateEdit',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=50)),
                ('emoji', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
