# Generated by Django 5.0.7 on 2024-07-30 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_interest', models.BooleanField(default=True)),
                ('family_interest_update', models.BooleanField(default=True)),
                ('family_hashtag_update', models.BooleanField(default=True)),
                ('family_comment', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alarm', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
