# Generated by Django 5.0.7 on 2024-07-30 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0002_alter_interest_created_at'),
        ('interest', '0002_interest_emoji_alter_interest_created_at'),
    ]

    operations = [
    ]
