# Generated by Django 5.0.7 on 2024-07-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0002_alter_interest_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='emoji',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
