# Generated by Django 5.0.7 on 2024-07-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0003_interest_emoji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='emoji',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
    ]
