# Generated by Django 5.0.7 on 2024-08-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0003_merge_20240730_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
